name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1 
    - name: Install package
      run: |
        sudo apt-get -qq install scons qemu || true
    - name: Startup scripts
      run: |
        python3 ./action-a/echo.py
